Add examples to README
xmidt-org/capacityset pull request #8
Opened 2019-10-05 00:04 UTC by mmichaelb

This pull request implements the requested application examples from #6. Furthermore, it also adds an example of how to `go get` the library within the installation process.

2019-10-05 00:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/xmidt-org/capacityset?pullRequest=8) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/xmidt-org/capacityset?pullRequest=8) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/xmidt-org/capacityset?pullRequest=8) it.</sub>

2019-10-06 22:16 UTC, kcajmagic requested changes
@mmichaelb thank you for you PR. I love your comments along with the example code. It is perfect. One minor change, instead of panicking when an additional item is added, it is a blocking call.

2019-10-06 22:16 UTC, kcajmagic commented on README.md
> +```
When the capacityset is set to 3 and the fourth item is added it is a blocking call and the above code will not finish, until another thread pops an item out of the set.

2019-10-08 13:51 UTC, mmichaelb commented on README.md
> +```
Thank you for your response. In my local example, the function panicked. But I think that was because there was no other routine active so Golang detected a permanently blocking lock.
I will adjust the comments ASAP and add a comment pointing out the concurrency involved in this blockage.

2019-10-11 18:01 UTC, kcajmagic approved these changes
Perfect, looks good.

2019-10-11 18:01 UTC, merged